apiVersion: v1

kind: Service
metadata:
  name: auth-svc
spec:
  selector:
    app: auth
  type: NodePort
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 8000
      nodePort: 30390